;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        comment-or-uncomment-region-or-line
        copy-to-pasteboard
        cut-to-clipboard
        end-of-buffer
        indent-new-comment-line
        paredit-forward-delete
        paredit-open-round
        paredit-splice-sexp-killing-backward
        paste-from-pasteboard
        tagedit-forward-slurp-tag
        tagedit-insert-dot
        tagedit-insert-equal
        tagedit-insert-exclamation-mark
        tagedit-insert-gt
        tagedit-insert-lt
        tagedit-insert-quote
        textmate-select-line
        yaml-electric-backspace
        ))

(setq mc/cmds-to-run-once
      '(
        copy-to-clipboard
        copy-to-pasteboard-2
        cycbuf-switch-to-next-buffer
        cycbuf-switch-to-previous-buffer
        describe-key
        eval-expression
        ido-find-file
        ido-switch-buffer
        indent-for-tab-command
        mac-mwheel-scroll
        mark-whole-buffer
        mc-test-fn
        move-to-window-line-top-bottom
        neotree-project-dir
        new-unnamed-buffer
        paste-from-clipboard
        paste-from-pasteboard
        smex
        ))
