;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        copy-to-pasteboard
        end-of-buffer
        indent-new-comment-line
        paredit-forward-delete
        paredit-open-round
        paredit-splice-sexp-killing-backward
        paste-from-pasteboard
        ))

(setq mc/cmds-to-run-once
      '(
        copy-to-clipboard
        copy-to-pasteboard-2
        cycbuf-switch-to-next-buffer
        cycbuf-switch-to-previous-buffer
        describe-key
        eval-expression
        mac-mwheel-scroll
        mark-whole-buffer
        mc-test-fn
        new-unnamed-buffer
        paste-from-clipboard
        paste-from-pasteboard
        smex
        ))
