(setq package-enable-at-startup nil)
(setq default-frame-alist
      '((height . 65)
        (width . 170)
        (left . 20)
        (top . 30)
        (font . "Monaspace Argon Frozen 13")
        (vertical-scroll-bars . nil)
        (horizontal-scroll-bars . nil)
        (tool-bar-lines . 0)))
